### PR TITLE
Added a suppressed gunshot to replace SMG.

### PR DESCRIPTION
**Pull request by JRHard771**
Exactly what it says on the tin. I made this gunshot with FL Studio and think it's a good replacement for the classic Doom DSPISTOL.

### CODE REVIEW

**Comment by caligari87** [comment]
Since the pistol (despite it's low alert range) is not actively suppressed in any meaningful way, I think it might be good to make a new sound definition and change the SMG to use it separately.

**Comment by JRHard771** [comment]
Duly noted. I've excluded the pistol from this change now and added the appropriate entries to SNDINFO and the SMG actor.

**Comment by MatthewTheGlutton** [comment]
I only added the rifle sounds because there aren't any in Doom, and the shotgun sound was reverted to an edited DSSHTGN after a while of having a total replacement.

Needless DSPISTOL replacement has been a longtime peeve I've had with Doom mods since maps were doing it in the 90s. Frankly, when I first closed this I read up to "replacement for the classic Doom DSPISTOL" and didn't bother reading the rest.

What is the basis for this new sound? Did you record this yourself? I've only listened to this so far on my cheap office headphones but if it could be made to sound something more like the suppressed version of DSPISTOL (while remaining qualitatively a clear improvement over just playing DSPISTOL at a reduced volume) I might consider it.

**Comment by caligari87** [comment]
Tried my own hand at this, created [three possible sounds for perusal](https://drive.google.com/drive/folders/1CbKZpE_UNLBopPDlExt7LL2WwceZeeNd?usp=sharing) (google drive folder).

1. `dssupsmg1.wav` is wholly a maniupulation of the doom pistol sound. I equalized down the bass frequencies and faded the tail sharply to get the initial impulse, then overlaid a quieter version of the original tail over it.

2. `dssupsmg2.wav` is the same as 1, except I blended in the impulse and tail of a suppressed Beretta M9 from [a video by hickok45](https://youtu.be/q61P1skurwc?t=525).

3. `dssupsmg2.wav` is again the same as 1, except this time I blended Josh's original sound for the primary impulse. 

All three are mono 22500 Hz, same as the original Doom pistol. The new sound itself is NOT clipped 3dB louder like the original pistol, so playing it at full volume will naturally be a little softer. The I used the high quality DSPISTOL from [Perkristian's HD doom SFX pack](http://www.perkristian.net/game_doom-sfx.shtml) as the base for the edit, for a higher-quality workflow.

**Pull request closed without merging**
